### ISSUE TITLE
Great idea, but needs parameters

### ISSUE THREAD

**Issue by Alphapage** [sirisian/ecmascript-static-constructor#1]
Hello,

```
class Multiton
{
    static constructor(param1,param2)
    {
         this.instances={p1:param1,p2:param2};
    }
    static constructor()
    {
        this.instances = {}; // instances is now a static member of Multiton
        // Multiton.instances = {}; // Same thing. Using "this" removes the need for using the name in the class
    }
    constructor(name)
    {
        if (this.instances.hasOwnProperty(name))
        {
            throw 'Multiton name already used';
        }
        this.instances[name] = this;
    }
}
```

And initialization:

```
Multiton('baz','baz2'); // or Multiton();
var foo = new Multiton('foo');
```

This is similar to:
```
var f=function(param1,param2){
    if (param1) f.instances={p1:param1,p2:param2};
     else f.instances={}
}
```

Thanks in advance for your opinion.

**Comment by sirisian** [comment]
I was thinking about parameters before, but I wasn't set on if using them to set static variables was the ideal use case. The more I think about it this is probably the only intuitive or logical use of parenthesis on a class.

If we allow this usage of a static constructor I believe it should be able to return like a normal function. While rare, I could use people using it to create views or other constructor-like calls.
